apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Template for nginx monitoring it needs an EPAgent
    iconClass: icon-openjdk
    tags: instant-app,agent
  name: nginxmonitor
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app_name: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app_name: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - args:
          - /nginxmonitor
          - -kubernetes_service=${NGINX_SERVICE_NAME}
          - -introscope_metric_label=${INTROSCOPE_LABEL}
          - -stats_uri=${NGINX_STATUS_URI}
          - -epagent_xml_endpoint=${WILY_EPAGENT_SERVICE_IP}
          env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: PROJECT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TZ
            value: ${TZ}
          image: {TAGGED_IMAGE}
          imagePullPolicy: Always
          name: ${APP_NAME}
          resources:
            limits:
              memory: 6M
            request:
              memory: 6M
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/metadata
            name: podinfo
            readOnly: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - metadata:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              name: labels
            - fieldRef:
                fieldPath: metadata.annotations
              name: annotations
          name: podinfo
  status: {}
parameters:
- description: Application name
  displayName: Application Name
  name: APP_NAME
  required: true
- description: Wily EPAgent Service IP, the Service name is [SERVICE_NAME]-xml:8000, your project must have an EPAgent pod deployed
  displayName: Wily EPAgent Service IP 
  name: WILY_EPAGENT_SERVICE_IP
  required: true
- description: nginx status Service Name, tipically 81, for ej. nginx-status.globalpaas-dev.endpoints, this is the service that you want to monitor
  displayName: nginx status Service Name, service name format must be [SERVICE]-status.[PROJECT_NAME].endpoints
  name: NGINX_SERVICE_NAME
  required: true
- description: Introscope metric's label, this label is used to group nginx metrics in a folder, we recommed to use the nginx service name
  displayName: Introscope metric's label
  name: INTROSCOPE_LABEL
  required: true
  value: nginx_CHANGE
- description: nginx status URI, by default the URI is nginx_status
  displayName: nginx status URI
  name: NGINX_STATUS_URI
  value: nginx_status
- description: TimeZone for the running containers.
  displayName: TimeZone
  name: TZ
  value: Europe/Madrid